# -*- coding: utf-8 -*-
"""predictivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_xp4rluV_jXjUQhF2PPP3y4rIkkDV6J
"""




"""# Predicción de ESCNNA (Clasificación)

1. Preparación de Datos
2. División de los datos 70-30
3. Aprendizaje del Modelo
4. Evaluación del Modelo: matriz de confusion, P,R, ROC
5. Guardar el modelo

* El despliegue se realiza en otro jupyter_notebook
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

"""# 1. Preparación de Datos

"""

#Cargamos los datos
data = pd.read_excel("dataset_final.xlsx", sheet_name="Data")
data.head()

data.info()

#Corrección tipos de datos
data['DEPARTAMENTO']=data['DEPARTAMENTO'].astype('category')
data['ARTICULO']=data['ARTICULO'].astype('category')
data['CIRCUNSTACIA_DE_LA_CAPTURA']=data['CIRCUNSTACIA_DE_LA_CAPTURA'].astype('category')
data['GENERO']=data['GENERO'].astype('category')
data['Riesgo_Departamento']=data['Riesgo_Departamento'].astype('category')
data['Momento_Delito']=data['Momento_Delito'].astype('category')
data['Tipo_Victima']=data['Tipo_Victima'].astype('category')
data['Tipo_Delito']=data['Tipo_Delito'].astype('category')
data['Entorno']=data['Entorno'].astype('category')
data['Reincidencia']=data['Reincidencia'].astype('category')


data.info()

# Instalar pandas profiling

#!pip install ydata-profiling

# Cargar librería para Profiling
#from pandas_profiling import ProfileReport

#profile_data=ProfileReport(data, minimal=False) # minimal=True
#profile_data

#Guardamos en html el perfilado de datos
#profile_data.to_file(output_file="output.html")

data['Reincidencia'].value_counts().plot(kind='bar')

"""##BALANCEO DE LA VARIABLE OBJETIVO"""

#La clase minoritaria tendrá el 50% del tamaño de la clase mayoritaria, adicionando datos sintéticos

from imblearn.over_sampling import SMOTEN, SMOTENC


# 1. SEPARAR VARIABLES
X = data.drop("Reincidencia", axis=1)
Y = data['Reincidencia']

# 2. ELECCIÓN DEL MÉTODO
# Si TODAS son categóricas, usamos SMOTEN:
sampler = SMOTEN(
    sampling_strategy=0.5, # La clase "Si" será el 50% de la "No"
    k_neighbors=2,         # Útil para grupos pequeños
    random_state=42
)


# 3. APLICAR EL BALANCEO
X_res, y_res = sampler.fit_resample(X, Y)

# 4. RECONSTRUIR EL DATAFRAME BALANCEADO
data_bal = pd.DataFrame(X_res, columns=X.columns)
data_bal['Reincidencia'] = y_res

# 5. VISUALIZACIÓN DE RESULTADOS
print("Distribución original:\n", Y.value_counts())
print("\nNueva distribución:\n", data_bal['Reincidencia'].value_counts())

data_bal['Reincidencia'].value_counts().plot(
    kind='bar',
    color=['skyblue', 'salmon'],
    title='Variable Reincidencia Balanceada (50%)'
)
plt.ylabel('Cantidad de Registros')
plt.show()

data_bal.head()

"""### Codificamos la variable objetivo (No=0, Si=1)"""

# Codificamos la variable objetivo (No=0, Si=1)
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data_bal["Reincidencia"] = labelencoder.fit_transform(data_bal["Reincidencia"])
data_bal.head()

data_bal.columns

"""###Dummies para las variables predictoras"""

#Dummies para las variables predictoras
data_bal = pd.get_dummies(data_bal, columns=['DEPARTAMENTO', 'ARTICULO', 'CIRCUNSTACIA_DE_LA_CAPTURA', 'Riesgo_Departamento', 'Momento_Delito', 'Tipo_Victima', 'Tipo_Delito',
       'Entorno'], drop_first=False, dtype=int)
data_bal = pd.get_dummies(data_bal, columns=['GENERO'], drop_first=True, dtype=int)

data_bal.head()

"""#2. División 70-30"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data_bal.drop("Reincidencia", axis = 1) # Variables predictoras
Y = data_bal['Reincidencia'] #Variable objetivo
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y) #Muestreo estratificado
Y_train.value_counts().plot(kind='bar')

"""#3. Aprendizaje con el 70% y Evaluación con el 30%"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn.tree import DecisionTreeClassifier #DecisionTreeRegressor

modelTree = DecisionTreeClassifier(criterion='gini',min_samples_leaf=10, max_depth=9, class_weight='balanced', random_state=42) #gini, entropy
modelTree.fit(X_train, Y_train) #70% train

from sklearn.tree import plot_tree
plt.figure(figsize=(30,20)) #Tamaño de la imagen
plot_tree(modelTree, feature_names=X_train.columns.values, class_names=labelencoder.classes_, rounded=True,  fontsize=8, filled=True)
plt.show()

#Evaluación 30% (X_test)
from sklearn import metrics

Y_pred = modelTree.predict(X_test) #30% Test
print(Y_pred)

exactitud=metrics.accuracy_score(y_true=Y_test, y_pred=Y_pred)
print(exactitud)

#Matriz de confusion
from sklearn import metrics

cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
cm

#Plot de la matriz de confusion
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

metrics.RocCurveDisplay.from_estimator(modelTree,X_test, Y_test)

from sklearn.metrics import roc_auc_score

# NO uses Y_pred (que son 0 y 1)
# USA las probabilidades de la clase positiva (clase 1)
Y_prob = modelTree.predict_proba(X_test)[:, 1]

auc_score = roc_auc_score(Y_test, Y_prob)
print(f"Nuevo AUC: {auc_score}")

"""# **KNN**

"""

#Aprendizaje KNN con 70%
from sklearn.neighbors  import KNeighborsClassifier #KNeighborsRegressor

modelKnn = KNeighborsClassifier(n_neighbors=10, metric='minkowski')#euclidean, minkowski
modelKnn.fit(X_train, Y_train) #70%

#Evaluación de Knn con 30%
from sklearn import metrics

Y_pred = modelKnn.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelKnn,X_test, Y_test)

"""# **Red Neuronal**

"""

from sklearn.neural_network import MLPClassifier #MLPRegressor

#Solo se configura capas ocultas, no se configura capa de entrada y de salida
#activation -> función activación de la oculta: tanh, logistic, linear, relu
#hidden_layer_sizes=5,7 -> dos capas ocultas con 5 neuronas y 7 neuronas
#learning_rate-> tamaño del paso constante o decreciente (constant, adaptive)
#learning_rate_init-> valor tasa de aprendizaje
#momentum-> valor momentum
#max_iter-> iteaciones
#random_state-> semilla para generacion numeros seudoaletorios
modelNN = MLPClassifier(activation="relu",hidden_layer_sizes=(30), learning_rate='constant',
                     learning_rate_init=0.01, momentum= 0.03, max_iter=500, random_state=20)

modelNN.fit(X_train, Y_train) #70% normalizados

#Evaluación de Red Neuronal
from sklearn import metrics

Y_pred = modelNN.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelNN,X_test, Y_test)

"""# **SVM**

"""

#SVM
from sklearn.svm import SVC # SVR

modelSVM = SVC(kernel='poly') #'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'
modelSVM.fit(X_train, Y_train) #70%

#Evaluación de SVM
from sklearn import metrics

Y_pred = modelSVM.predict(X_test) #20%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelSVM,X_test, Y_test)

"""# **Regresión Logística**"""

from sklearn.linear_model import LogisticRegression

# Creación del modelo de Regresión Logística
modelLR = LogisticRegression(max_iter=100, random_state=2)
modelLR.fit(X_train, Y_train) # 70% normalizados

#Evaluación de Reg logística
from sklearn import metrics

Y_pred = modelLR.predict(X_test) #20%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelLR,X_test, Y_test)



"""# **5.Guardamos el modelo**
-Se entrena  modelo final con 100% de los datos(X,Y)
"""

#Entrenamos modelo final
modelNN.fit(X,Y) #100%

import pickle
filename='modelo-class.pkl'
variables=X.columns.values
pickle.dump([modelNN, labelencoder, variables], open(filename, 'wb'))